# Ivana Setiawan

Engineer, Hacker & Founder.
I'm a polyglot programmer experienced in JavaScript, Python, PHP, and PostgreSQL, with a focus on crafting seamless user experiences. 
I excel at merging code and design to create impactful digital solutions. My passion is learning and mastering new languages and frameworks to 
innovate in software engineering.

My ongoing projects are Avstarna, Nite-Nite, Venopi, & Ruma.
https://www.avstarna.com ~ https://nite-nite.com/ ~ https://www.venopi.com ~ https://ruma-living.com/

## Usage

To run the project, install jekyll & then bundle install to install all the dependency:
```bash
gem install bundler jekyll
bundle install
```

Run the project:
```bash
bundle exec jekyll serve
```

Draft blog:
```bash
bundle exec jekyll serve --draft
```

Run tailwind for styling:
```bash
npx tailwindcss -i ./assets/main.css -o ./assets/dist/main.css --watch
```
